Lecture 1 setup and product dao
garist09/phoneshop-servlet-api pull request #1
Opened 2022-01-25 14:50 UTC by garist09

2022-01-26 11:39 UTC, devjohnsmith1 requested changes

2022-01-26 11:39 UTC, devjohnsmith1 commented on pom.xml
> -  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
Исправь форматирование

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +import java.util.*;
лишние импорты

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    private long maxId;
для чего нужен maxId?

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        saveSampleProducts();
можем ли мы вынести этот метод из конструктора?

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .filter(product -> id.equals(product.getId()))
что если id пустой?

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        return product.getStock() > 0;
что если stock = null?

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .ifPresentOrElse(element -> products.set(product.getId().intValue(), product),  () -> {
должно ли быть соответствие id и положения в списке?

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                .collect(Collectors.toList());
как сделать удаление проще?

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    private synchronized  void saveSampleProducts() {
нужна ли здесь синхронизация? (+ форматирование)

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +    }
слишком длинный конструктор

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        request.getRequestDispatcher("/WEB-INF/pages/productList.jsp").forward(request, response);
выноси hardcode значения в константы. + можно ли элегантнее печатать стэктрейс эксепшна?

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/webapp/WEB-INF/pages/productList.jsp
> +    </tr>
formatting

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/main/webapp/WEB-INF/pages/productList.jsp
> +          <img class="product-tile" src="${product.imageUrl}" alt="Phone image">
выноси hardcode строки (property)

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +import static org.junit.Assert.*;
нужны ли все ассерты?

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
>      private ProductDao productDao;
почему используем реальное Дао?

2022-01-26 11:39 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertEquals(product, productDao.getProduct((long) listSize - 1));
константы + название тестовых методов - should....when.....then

2022-01-28 22:06 UTC, devjohnsmith1 requested changes

2022-01-28 22:06 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
>                  .orElseThrow(ProductNotFoundException::new);
раздели 2 сценария - id не валидный, продукта нет. Когда используем Exception, когда Optional

2022-01-28 22:06 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            return false;
форматирование (скобки)

2022-01-28 22:06 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                        product.setId((long) (Math.random() * 1000));
magic numbers + нет уверенности в том, что каждый раз будут сетаться новые id. Перепиши задание id (UID generator или порядковый номер)

2022-01-28 22:06 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +            throw new ProductNotFoundException();
форматирование (скобки). + Почему мы в delete кидаем эксепшн, что продукта нет?

2022-01-28 22:06 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +        }
исправь форматирование + замени magic numbers. Исключительная ли это ситуация?

2022-01-28 22:06 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertNotEquals(product, productDao.getProduct(1L));
выноси константы

2022-01-28 22:06 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +import static org.mockito.Mockito.*;
лишние импорты

2022-01-28 22:06 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
>      private ProductDao productDao;
замокай product dao + junit runner используй

2022-01-29 19:55 UTC, garist09 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        saveSampleProducts();
Вы на code review сказали, что можно не выносить данный метод и оставить его так

2022-01-29 19:58 UTC, garist09 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
>      private ProductDao productDao;
Использование productDao в качестве заглушки не дает возможности тестирования его методов

2022-01-30 13:42 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertNotEquals(product, productDao.getProduct(L1));
тестовый метод должен тестировать 1 сценарий, разбей тесты на подтесты

2022-01-30 13:43 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        assertNotEquals(SIEMENS_C_61, result.getDescription());
разбей тестовый метод на несколько

2022-01-31 13:03 UTC, devjohnsmith1 approved these changes

2022-01-31 14:50 UTC, merged