Lecture3
garist09/phoneshop-servlet-api pull request #3
Opened 2022-02-07 18:10 UTC by garist09

2022-02-08 13:51 UTC, devjohnsmith1 requested changes

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +    public static final String NON_POSITIVE = "Quantity is non-positive";
добавляй в название переменных больше конкретики - NON_POSITIVE_MESSAGE, _ERROR, _PROPERTY и тд

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +    public static final int INT0 = 0;
переименуй переменную - в чём её функционал?

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +                .ifPresentOrElse(cartItem -> cartItem.setQuantity(cartItem.getQuantity()+quantity),
форматирование (знак +)

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +    public void add(Product product, int quantity) throws ProductNotFoundException, IdNotFoundException, IllegalArgumentException {
функциональный метод не должен быть в сущности, перенеси в сервис

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/service/CartService.java
> +public interface CartService {
вынеси сервис в отдельную папку -> почему сервис хранится в model? dao, exceptions...., service(s)

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/service/impl/CartServiceImpl.java
> +    public static final String CART_ATTRIBUTE = "CartServiceImpl.CART";
переименуй атрибут: cart, sessionCart...

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/service/impl/CartServiceImpl.java
> +    public static CartService getInstance() {
подумай над синхронизацией методов

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/service/impl/CartServiceImpl.java
> +    public void addProduct(HttpServletRequest request, String id, int quantity) throws IdNotFoundException, OutOfStockException, ProductNotFoundException, IllegalArgumentException {
id чего? Переименуй, чтобы понимать, для чего нужен атрибут

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/service/impl/CartServiceImpl.java
> +        if (Objects.isNull(id)) {
А если id - пустая строчка? Строчка из пробелов?

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +            if (Objects.isNull(product.getId())) {
пропускает id=""

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/RecentlyViewedProducts.java
> +    public static final int INT0 = 0;
придумай осознанные имена переменным

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/RecentlyViewedProducts.java
> +    }
подумай, нужен ли тебе здесь синглтон и нужно ли его синхронизировать

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/RecentlyViewedProducts.java
> +}
функциональные методы должны быть в сервисах, выноси их из POJO

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/CartServlet.java
> +public class CartServlet extends HttpServlet {
название должно быть соответствующее - HttpSessionCartServlet и тд

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +    public static final String AVAILABLE = "Available: ";
все переменные выглядят одинаково - добавь специфичности. Где message, attribute, page и тд

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            request.setAttribute(ERROR, AVAILABLE + ex.getStock());
не раскрывай stock пользователю. Можешь логировать для разработчиков, но пользователю просто скажи, что не хватает такого кол-ва

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/service/impl/CartServiceImpl.java
> +public class CartServiceImpl implements CartService {
учитывай специфику - HttpSessionCartServiceImpl, например

2022-02-08 13:51 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/service/impl/CartServiceImpl.java
> +public class CartServiceImpl implements CartService {
пропиши юнит тесты для новых сервисов

2022-02-08 13:54 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/RecentlyViewedProducts.java
> +}
что если продукт уже есть в корзине?

2022-02-09 16:51 UTC, garist09 commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            request.setAttribute(ERROR, AVAILABLE + ex.getStock());
Мы выводим stock пользователю в описании товара. Почему нельзя говорить пользователю кол-во товара? Как он узнает сколько можно заказать. Например, на 21 веке при добавлении товаров большего кол-ва, выводится доступное кол-во товаров

2022-02-13 06:18 UTC, devjohnsmith1 requested changes

2022-02-13 06:18 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +        ResourceBundle mybundle = ResourceBundle.getBundle(ERROR_ATTRIBUTE, request.getLocale());
переназови mybundle + java naming convention

2022-02-13 06:18 UTC, devjohnsmith1 commented on src/main/webapp/WEB-INF/classes/error.properties
> +nonPositiveQuantity = Quantity is non-positive
naming convention. Проперти обычно называются addToCart.success.message, error.not.positive.message. + Проперти логично располагать не в папке classes

2022-02-14 08:59 UTC, devjohnsmith1 approved these changes

2022-02-14 13:37 UTC, merged