Lecture4
garist09/phoneshop-servlet-api pull request #5
Opened 2022-02-15 11:56 UTC by garist09

2022-02-17 12:19 UTC, devjohnsmith1 requested changes

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/exception/QuantityOfBoundException.java
> +public class QuantityOfBoundException extends RuntimeException{
Quantity OUT of Bound?

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/cart/Cart.java
> +        cartItemList = cartItemList.stream().filter(this::quantityComparing).collect(Collectors.toList());
выноси бизнес-логику из объектов в сервисы

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/PriceHistoryItem.java
> +        if (o == null || getClass() != o.getClass()) return false;
ФИГУРНЫЕ  {
        СКОБКИ 
}

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/PriceHistoryItem.java
> +        PriceHistoryItem that = (PriceHistoryItem) o;
кто такие that и o?

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +    private static String generateUUID() {
не изобретай велосипед, используй готовый рандомизатор

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +        return stock == product.stock && Objects.equals(id, product.id) && Objects.equals(code, product.code) && Objects.equals(description, product.description) && Objects.equals(price, product.pric
разбивай большие строки

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +        Product product = (Product) o;
СКОБКИ

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartService.java
> +        validation(productId, quantity);
методы - это глаголы. Что делает метод?

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartService.java
> +            throw new IllegalArgumentException(NON_POSITIVE_MESSAGE);
сообщение должно быть в Resource Bundle

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartService.java
> +            products.removeIf(x -> x.getProduct().equals(product));
что такое x?

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartService.java
> +    public void removeProduct(HttpServletRequest request, String productId, int quantity) throws IdNotFoundException, IllegalArgumentException, OutOfStockException {
большая строка - разбивай

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartService.java
> +            List<CartItem> products = getCart(request).getProducts();
почему getProducts возвращает список СartItems?

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/HttpSessionCartServlet.java
>  public class HttpSessionCartServlet extends HttpServlet {
наименования для сервлетов - должны понимать, что за страница. PDP, PLP, CartPage. Для чего? - delete, update и тд

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/HttpSessionCartServlet.java
> +                }
раздели по двум сервлетам, как в задании

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/MiniCartServlet.java
> +public class MiniCartServlet extends HttpServlet {
PageServlet

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +    }
разделяй визуально - трудно читать один кусок кода

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        ResourceBundle errorMessages = ResourceBundle.getBundle(ERROR_ATTRIBUTE, request.getLocale());
вынеси в инит метод

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +            return;
для чего тут return?

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/webapp/WEB-INF/pages/cart.jsp
> +                <td></td>
используй лучше сolspan, чтобы не дублировать

2022-02-17 12:19 UTC, devjohnsmith1 commented on src/main/webapp/WEB-INF/pages/product.jsp
> +            </c:if>
лишнее форматирование

2022-02-17 12:22 UTC, devjohnsmith1 commented
+ добавь юнит тесты для новых сервисов (оба сценария) и переназови имплементацию сервисов. (Impl на конце)

2022-02-17 19:09 UTC, garist09 commented on src/main/java/com/es/phoneshop/exception/QuantityOfBoundException.java
> +public class QuantityOfBoundException extends RuntimeException{
+

2022-02-17 19:12 UTC, garist09 commented on src/main/java/com/es/phoneshop/model/product/PriceHistoryItem.java
> +        if (o == null || getClass() != o.getClass()) return false;
+

2022-02-17 19:14 UTC, garist09 commented on src/main/java/com/es/phoneshop/model/product/PriceHistoryItem.java
> +        PriceHistoryItem that = (PriceHistoryItem) o;
+

2022-02-17 19:14 UTC, garist09 commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +        Product product = (Product) o;
+

2022-02-17 19:14 UTC, garist09 commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +        return stock == product.stock && Objects.equals(id, product.id) && Objects.equals(code, product.code) && Objects.equals(description, product.description) && Objects.equals(price, product.pric
+

2022-02-17 19:14 UTC, garist09 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartService.java
> +        validation(productId, quantity);
+

2022-02-17 19:14 UTC, garist09 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartService.java
> +            products.removeIf(x -> x.getProduct().equals(product));
+

2022-02-17 19:14 UTC, garist09 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartService.java
> +            throw new IllegalArgumentException(NON_POSITIVE_MESSAGE);
+

2022-02-17 19:14 UTC, garist09 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartService.java
> +    public void removeProduct(HttpServletRequest request, String productId, int quantity) throws IdNotFoundException, IllegalArgumentException, OutOfStockException {
+

2022-02-17 19:14 UTC, garist09 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartService.java
> +            List<CartItem> products = getCart(request).getProducts();
+

2022-02-17 19:15 UTC, garist09 commented on src/main/java/com/es/phoneshop/web/HttpSessionCartServlet.java
>  public class HttpSessionCartServlet extends HttpServlet {
+

2022-02-17 19:15 UTC, garist09 commented on src/main/webapp/WEB-INF/pages/cart.jsp
> +                <td></td>
+

2022-02-17 19:15 UTC, garist09 commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        ResourceBundle errorMessages = ResourceBundle.getBundle(ERROR_ATTRIBUTE, request.getLocale());
+

2022-02-17 19:16 UTC, garist09 commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +    }
+

2022-02-17 19:16 UTC, garist09 commented on src/main/webapp/WEB-INF/pages/product.jsp
> +            </c:if>
+

2022-02-19 14:59 UTC, devjohnsmith1 requested changes

2022-02-19 14:59 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartServiceImpl.java
> +    private void checkingProductIdAndQuantity(String productId, int quantity)
check..., validate..., (что делать? конкретно)

2022-02-19 14:59 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/service/impl/HttpSessionCartServiceImpl.java
> +    private boolean quantityComparing(CartItem cartItem) {
naming convention. Что "сравнивает" этот метод? Обычно boolean метод отвечает, правда или ложь - isQuantityValid, hasSessionCart, isLessZero

2022-02-19 14:59 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/service/HttpSessionCartServiceImplTest.java
>      public static final int QUANTITY3 = 3;
что такое QUANTITY9?

2022-02-19 16:42 UTC, merged