Lecture5
garist09/phoneshop-servlet-api pull request #7
Opened 2022-02-22 19:35 UTC by garist09

2022-02-23 12:13 UTC, devjohnsmith1 requested changes
+ проверяй форматирования и читаемость методов

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/dao/ArrayListOrderDao.java
> +            throw new IdNotFoundException();
как нам понять, где не найден id продукта, а где id ордера?

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/order/Order.java
> +    private static final Random random;
используй лучше Secure Random

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/order/Order.java
> +public class Order implements Serializable {
методы set... не должны делать что-либо, кроме проставления значения атрибута. Выноси логику такого рода в билдер

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/security/impl/DosProtectionServiceImpl.java
> +        startDate = new Date();
то есть startDate мы считаем с момента инициализации сервиса?

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/security/impl/DosProtectionServiceImpl.java
> +        if ((endDate.getTime() - startDate.getTime()) > TimeUnit.MINUTES.toMillis(TIME_TO_RESET_REQUEST_COUNT_OF_USERS)) {
сравнивай даты через соответствующие методы, без арифметических операций

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/security/impl/DosProtectionServiceImpl.java
> +    private static final long THRESHOLD = 10;
такие параметры должны быть конфигурабельны - выноси в отдельный проперти файл. + в задании было кол-во запросов = 20

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/security/impl/DosProtectionServiceImpl.java
> +            Set<String> setOfBannedIp = Set.copyOf(bannedIp.keySet());
зачем тебе итерироваться по ключам? У тебя ведь есть Map. + циклы -> Stream API

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/service/impl/OrderServiceImpl.java
> +        return new BigDecimal(30);
вынеси в отдельную проперти

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/service/impl/OrderServiceImpl.java
> +    public Order createOrderFromCart(Cart cart) {
почему клонируем не всю корзину, а только отдельно карт айтемы?

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/CheckoutPageServlet.java
> +        orderDao = ArrayListOrderDao.getInstance();
нечитаемо - выноси логику, не связанную с инициализацией, в отдельный метод. + константы

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/CheckoutPageServlet.java
> +        }
Stream API

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/CheckoutPageServlet.java
> +        request.setAttribute(DELIVERY_DATES_ATTRIBUTE, deliveryDates);
прямо читается отдельный метод

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/CheckoutPageServlet.java
> +                .setPaymentMethod(request.getParameter(PAYMENT_METHOD_PARAMETER));
выноси отдельно

2022-02-23 12:13 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/CheckoutPageServlet.java
> +    private void setErrors(HttpServletRequest request, List<String> errors) {
это валидация. + добавь валидацию не только на пустоту, но и через Regex (не все значения от юзера валидные)

2022-02-23 17:49 UTC, garist09 commented on src/main/java/com/es/phoneshop/dao/ArrayListOrderDao.java
> +            throw new IdNotFoundException();
+

2022-02-26 08:46 UTC, devjohnsmith1 approved these changes

2022-02-26 13:44 UTC, merged